### ISSUE TITLE
Amazfit Rainbow

### ISSUE THREAD

**Issue by Horatius80** [ghtalpo/py_amazfit_tools#22]
Hi ghtalpo,

I tried two of Your branches (master, gtr) but I am not able to decompile correctly the Amazfit Rainbow Watchface i got this log (log is generated with master version)
[Amazfit_RainbowCircle.log](https://github.com/ghtalpo/py_amazfit_tools/files/4067595/Amazfit_RainbowCircle.log)

I am using Python 3.8 x64 and latest Pillow 7.0.0 thanx for help

Best regards Horatius80

**Comment by Horatius80** [comment]
And when i try to use win32 release i got this log
[Amazfit_RainbowCircle(win32-main.exe).log](https://github.com/ghtalpo/py_amazfit_tools/files/4067648/Amazfit_RainbowCircle.win32-main.exe.log)

**Comment by kampanita** [comment]
I used SashaCX75's tool ( with or without python ) and it's able to decompile and recompile it again.
When decompiled :
[Amazfit_RainbowCircle.log]

i get this .json file
(https://github.com/ghtalpo/py_amazfit_tools/files/4069782/Amazfit_RainbowCircle.log)

but when trying to recompile again, some of the new parameters like "goal2" dissappeared from .json file when processed ( i think that sashaCX75's implementation of python code does the trick, when does not recognize something, it clears before trying to pack it )
as you can see at this other log ( repacking )

[Amazfit_RainbowCircle(1)_packed.log](https://github.com/ghtalpo/py_amazfit_tools/files/4069792/Amazfit_RainbowCircle.1._packed.log)

**Comment by ghtalpo** [comment]
> Hi ghtalpo,
> 
> I tried two of Your branches (master, gtr) but I am not able to decompile correctly the Amazfit Rainbow Watchface i got this log (log is generated with master version)
> [Amazfit_RainbowCircle.log](https://github.com/ghtalpo/py_amazfit_tools/files/4067595/Amazfit_RainbowCircle.log)
> 
> I am using Python 3.8 x64 and latest Pillow 7.0.0 thanx for help
> 
> Best regards Horatius80

can you provide me a link for the WF?

**Comment by kampanita** [comment]
https://amazfitwatchfaces.com/gtr/view/2876

**Comment by Horatius80** [comment]
Here is the original from Amazfit aplication (compressed)
[Amazfit_RainbowCircle.zip](https://github.com/ghtalpo/py_amazfit_tools/files/4107837/Amazfit_RainbowCircle.zip)

**Comment by ghtalpo** [comment]
fixed in latest commit
