### ISSUE TITLE
Delimiter image on Time section not visible on preview and design

### ISSUE THREAD

**Issue by nightwatch75** [ghtalpo/py_amazfit_tools#5]
The delimiter image defined on json is not visible on preview and design canvas
for example

```
 "Delimiter": {
            "X": 192,
            "Y": 152,
            "ImageIndex": 12
        }
```

despite this the image is present in the final file bin, the problem is only on editor

**Comment by ghtalpo** [comment]
can you provide your packages for test? there's no such error so far.

**Comment by nightwatch75** [comment]
Sorry, was an error on png format!
