### ISSUE TITLE
Icon mapping json->bin

### ISSUE THREAD

**Issue by nightwatch75** [ghtalpo/py_amazfit_tools#6]
[demo.json.txt](https://github.com/ghtalpo/py_amazfit_tools/files/3605702/demo.json.txt)

Packing a bin for gtr47mm from demo.json (example_watchface) adding bluetooth section (and pngs as well) results in a always BT OFF icon displayed.

**Comment by nightwatch75** [comment]
Nevermind, huami has updated the fw of the gtr, now no status icon corresponds to the Json ... this is what happens now:

"DoNotDisturb" in Json results in Bluetooth icon in the bin
"Alarm" in Json results in Lock icon
"Bluetooth" in Json results in Alarm icon
"Lock" in Json result in DoNotDisturb icon...

what a mess!

**Comment by titanzx** [comment]
#14 Fixed

**Comment by ghtalpo** [comment]
checkout gtr branch
